export { normalizeCategory, inferCategoryFromTitle, SEARCH_CATEGORY_SLUGS } from "@/lib/news/category-mapper";
export { dedupeArticles, isDuplicateArticle, heuristicDuplicateStrategy } from "@/lib/news/duplicate-detector";
export type { DuplicateStrategy } from "@/lib/news/duplicate-detector";
export { SOURCES, getSourceById, findSourceIdByName } from "@/lib/news/sources";
export { slugify, buildArticleId, makeUniqueSlug } from "@/lib/news/slug";
export { TTLCache } from "@/lib/news/ttl-cache";
export { resolveArticleImage, pickBestImageUrl, isAcceptableImageUrl } from "@/lib/news/image-fallback";
export type { ImageCandidate } from "@/lib/news/image-fallback";
export { getSourceLogo, DEFAULT_SOURCE_LOGO } from "@/lib/news/source-logos";
export { formatPublishedDate } from "@/lib/news/date-format";
export { toCategoryNewsItem } from "@/lib/news/ui-adapter";
export { FEED_SOURCES } from "@/lib/news/feed-sources";
export type { FeedSourceConfig } from "@/lib/news/feed-sources";
export { estimateReadingTime } from "@/lib/news/reading-time";
export { resolveTrustScore } from "@/lib/news/trust-score";
export { calculateTrendingScore } from "@/lib/news/trending-score";
export type { TrendingSignals, TrendingScoreParams } from "@/lib/news/trending-score";
export { fetchWithTimeout, classifyHttpStatus, ProviderHttpError } from "@/lib/news/fetch-with-timeout";
export type { ProviderFailureKind } from "@/lib/news/fetch-with-timeout";
export { fetchOgImage } from "@/lib/news/og-image";
export { resolveFallbackImageForCategory } from "@/lib/news/image-fallback";
export { searchStockImage } from "@/lib/news/stock-image-provider";
export type { StockImageProviderId, StockImageResult } from "@/lib/news/stock-image-provider";
export { fetchArticleContent, MIN_ACCEPTABLE_CONTENT_LENGTH } from "@/lib/news/article-content";
export { splitIntoParagraphs } from "@/lib/news/paragraph-split";
