-- Developer Hub expansion - curated, high-quality resources across all six
-- catalog categories (Certifications, Courses, Learning Paths, Developer
-- Tools, Roadmaps, Cheat Sheets), matching the curation bar already used
-- for the GitHub Explorer library (migrations 0026/0027/0030).
--
-- Part 1 fixes a real schema gap: `catalog_items` (0022) has no `tags` or
-- "why recommended" column, so an editorial pass here would otherwise have
-- nowhere real to store that data. Adds `tags text[]` and `editor_notes
-- text`, mirroring the `repositories` table's existing editorial columns
-- (0024/0026) - additive and idempotent via `ADD COLUMN IF NOT EXISTS`.
--
-- Part 2 adds 48 new curated items (8 per category except Learning Paths
-- at 5 and Developer Tools/Roadmaps at 10/9) - every item audited against
-- the full existing catalog (every `catalog_items` insert across 0022 and
-- 0030) to guarantee zero duplicates. Every URL points at the resource's
-- own official domain (verified directly, not taken from a third-party
-- aggregator) or, where no single vendor owns the resource (e.g. roadmap.sh
-- roadmaps, devhints.io references), the canonical/most-recommended source.
-- `official` reflects whether the resource is published by the actual
-- provider/vendor (true) or is a well-regarded community resource (false).
-- Every `editor_notes` is original commentary in Virexa's own voice, never
-- copied from the source's own marketing copy.
--
-- Idempotent: every insert is `on conflict (id) do nothing` against a
-- stable, real id ("resource_type:slug"), so re-running this is a safe
-- no-op. `ADD COLUMN IF NOT EXISTS` makes Part 1 safe to re-run too.

-- ============================================================================
-- Part 1: add editorial columns to catalog_items
-- ============================================================================

alter table public.catalog_items
  add column if not exists tags text[] not null default '{}',
  add column if not exists editor_notes text not null default '';

comment on column public.catalog_items.tags is
  'Editorial topic tags for filtering/display, e.g. {"AWS","Cloud","Architecture"} - mirrors repositories.tags (migration 0024).';

comment on column public.catalog_items.editor_notes is
  'Original "why it''s recommended" editorial blurb, written in Virexa''s own voice - mirrors repositories.editor_notes (migration 0026).';

-- ============================================================================
-- Part 2a: Certifications, Courses, Learning Paths, Developer Tools and
-- Cheat Sheets - one shared insert shape (matches 0022's original column
-- list, with tags/editor_notes inserted before display_order).
-- ============================================================================

insert into public.catalog_items (id, resource_type, slug, title, provider, description, difficulty, price, url, emoji, featured, official, tags, editor_notes, display_order)
values
  -- Certifications (8 new - display_order continues from 0022's 0-9)
  ('certification:aws-certified-solutions-architect-professional', 'certification', 'aws-certified-solutions-architect-professional', 'AWS Certified Solutions Architect – Professional', 'Amazon Web Services', 'Advanced-level validation for designing complex, multi-account, hybrid AWS architectures at scale.', 'advanced', 'paid', 'https://aws.amazon.com/certification/certified-solutions-architect-professional/', '🏛️', true, true, '{"AWS","Cloud","Architecture"}', 'The certification hiring managers actually look for once you''re past the Associate level - expect deep, scenario-heavy questions on multi-account governance and cost optimization, not memorized service limits.', 10),
  ('certification:certified-kubernetes-application-developer', 'certification', 'certified-kubernetes-application-developer', 'Certified Kubernetes Application Developer (CKAD)', 'The Linux Foundation / CNCF', 'Hands-on validation of building, deploying and configuring cloud native applications for Kubernetes.', 'intermediate', 'paid', 'https://training.linuxfoundation.org/certification/certified-kubernetes-application-developer-ckad/', '☸️', false, true, '{"Kubernetes","Cloud Native","Certification"}', 'CKA proves you can run a cluster; CKAD proves you can build for one - the natural pairing for anyone shipping containerized apps rather than administering the infrastructure underneath them.', 11),
  ('certification:google-professional-cloud-architect', 'certification', 'google-professional-cloud-architect', 'Google Professional Cloud Architect', 'Google Cloud', 'Validates designing, developing and managing robust, secure, scalable solutions on Google Cloud.', 'advanced', 'paid', 'https://cloud.google.com/certification/cloud-architect', '🌐', true, true, '{"Google Cloud","Architecture","Certification"}', 'Consistently ranks among the highest-paying cloud certifications - the case-study exam format tests real architectural judgment, not just which button provisions a VM.', 12),
  ('certification:microsoft-azure-solutions-architect-expert', 'certification', 'microsoft-azure-solutions-architect-expert', 'Microsoft Certified: Azure Solutions Architect Expert (AZ-305)', 'Microsoft', 'Expert-level validation for designing infrastructure, data, business continuity and security solutions on Azure.', 'advanced', 'paid', 'https://learn.microsoft.com/en-us/credentials/certifications/azure-solutions-architect/', '🪟', false, true, '{"Azure","Cloud","Architecture"}', 'The natural next step after AZ-900 - requires an associate-level administering or developing cert first, so it signals genuine hands-on Azure depth rather than exam-cram knowledge.', 13),
  ('certification:isc2-cissp', 'certification', 'isc2-cissp', 'CISSP (Certified Information Systems Security Professional)', 'ISC2', 'The gold-standard credential for senior security practitioners, covering all eight domains of the CISSP Common Body of Knowledge.', 'advanced', 'paid', 'https://www.isc2.org/certifications/cissp', '🛡️', true, true, '{"Security","Certification","Management"}', 'Still the credential security leadership roles list as a hard requirement - the five-year experience prerequisite keeps it honest as a career-stage marker, not a weekend cram.', 14),
  ('certification:hashicorp-certified-vault-associate', 'certification', 'hashicorp-certified-vault-associate', 'HashiCorp Certified: Vault Associate', 'HashiCorp', 'Validates foundational skills in Vault for secrets management, encryption as a service and identity-based access.', 'intermediate', 'paid', 'https://developer.hashicorp.com/certifications/security-automation', '🔑', false, true, '{"Security","HashiCorp","Secrets Management"}', 'Secrets sprawl is a real production problem long before anyone plans for it - this is the credential for the engineer who actually owns fixing that, not just reading about Vault in a blog post.', 15),
  ('certification:linux-foundation-certified-sysadmin', 'certification', 'linux-foundation-certified-sysadmin', 'Linux Foundation Certified System Administrator (LFCS)', 'The Linux Foundation', 'Performance-based certification proving the skills to install, configure and troubleshoot Linux systems.', 'intermediate', 'paid', 'https://training.linuxfoundation.org/certification/linux-foundation-certified-sysadmin-lfcs/', '🐧', false, true, '{"Linux","SysAdmin","Certification"}', 'A live, hands-on exam on a real terminal rather than multiple choice - the closest thing to proving you can actually fix a broken box under time pressure.', 16),
  ('certification:professional-scrum-master-i', 'certification', 'professional-scrum-master-i', 'Professional Scrum Master I (PSM I)', 'Scrum.org', 'Validates a solid understanding of Scrum as described in the Scrum Guide, and how to apply it effectively.', 'beginner', 'paid', 'https://www.scrum.org/assessments/professional-scrum-master-i-certification', '🔁', false, true, '{"Agile","Scrum","Certification"}', 'Unlike some Agile certs, PSM I is graded purely on a tough assessment with no mandatory paid course required - so it actually filters for people who understand Scrum rather than just attended a class.', 17),

  -- Courses (8 new - display_order continues from 0030's 10-19)
  ('course:the-odin-project', 'course', 'the-odin-project', 'The Odin Project', 'The Odin Project', 'A free, full-stack open source curriculum covering web fundamentals through Ruby on Rails or Node.js.', 'beginner', 'free', 'https://www.theodinproject.com/', '🗿', true, false, '{"Web Dev","Full Stack","Open Source"}', 'The curriculum that doesn''t feel free - project-heavy, opinionated about which technologies actually matter, and refreshingly honest that becoming a developer takes real time.', 20),
  ('course:full-stack-open', 'course', 'full-stack-open', 'Full Stack Open', 'University of Helsinki', 'A deep, modern full-stack curriculum covering React, Redux, Node.js, GraphQL, TypeScript and testing - built by a real university.', 'intermediate', 'free', 'https://fullstackopen.com/en/', '🇫🇮', true, true, '{"React","Full Stack","GraphQL"}', 'University-rigor without the university - the closest thing to a real CS full-stack course syllabus, and it''s kept current with the actual React ecosystem instead of frozen circa 2019.', 21),
  ('course:mit-6-0001-intro-cs-python', 'course', 'mit-6-0001-intro-cs-python', 'Introduction to Computer Science and Programming in Python (6.0001)', 'MIT OpenCourseWare', 'MIT''s real, free introductory computer science course - problem sets, lecture videos and exams, taught in Python.', 'beginner', 'free', 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/', '🎓', false, true, '{"Computer Science","Python","MIT"}', 'The actual course MIT students take, not a repackaged version - if CS50 is the popular front door, this is the more rigorous one right next to it.', 22),
  ('course:google-machine-learning-crash-course', 'course', 'google-machine-learning-crash-course', 'Machine Learning Crash Course', 'Google', 'Google''s own fast-paced, practical introduction to machine learning - concepts, TensorFlow exercises and real case studies.', 'beginner', 'free', 'https://developers.google.com/machine-learning/crash-course', '🧪', false, true, '{"Machine Learning","Google","AI"}', 'The course Google''s own engineers use to onboard new hires into ML - dense, practical, and far more hands-on than its crash-course name suggests.', 23),
  ('course:machine-learning-specialization-coursera', 'course', 'machine-learning-specialization-coursera', 'Machine Learning Specialization', 'Coursera / DeepLearning.AI / Stanford', 'Andrew Ng''s newly rebuilt foundational ML specialization, updated for modern tooling and best practices.', 'beginner', 'paid', 'https://www.coursera.org/specializations/machine-learning-introduction', '📈', true, true, '{"Machine Learning","Coursera","Andrew Ng"}', 'The rebuilt, modernized successor to the original course that taught an entire generation of engineers ML - still the most-recommended starting point on forums full of people who''d know.', 24),
  ('course:frontend-masters', 'course', 'frontend-masters', 'Frontend Masters', 'Frontend Masters', 'In-depth, expert-taught video courses on JavaScript, frameworks, CSS and web performance - built for working developers, not beginners.', 'intermediate', 'paid', 'https://frontendmasters.com/', '🎥', false, true, '{"Frontend","JavaScript","Deep Dive"}', 'The instructors are usually the people who wrote the library you''re learning - noticeably deeper than typical bootcamp-style video courses, worth the subscription if frontend is your actual job.', 25),
  ('course:exercism', 'course', 'exercism', 'Exercism', 'Exercism', 'Free coding practice across 70+ languages with real mentor feedback on your solutions, not just automated test passes.', 'beginner', 'free', 'https://exercism.org/', '🧩', false, true, '{"Practice","Mentorship","Free"}', 'The mentored code review is the actual value here - a real person telling you your solution works but isn''t idiomatic is worth more than another green checkmark.', 26),
  ('course:boot-dev', 'course', 'boot-dev', 'Boot.dev', 'Boot.dev', 'An interactive, project-based backend engineering curriculum covering Python, Go, SQL, Docker, Kubernetes and system design fundamentals.', 'beginner', 'paid', 'https://www.boot.dev/', '⚙️', false, true, '{"Backend","Python","Go"}', 'Built specifically to fill the gap every frontend-heavy bootcamp leaves - almost nowhere else teaches backend fundamentals this directly, with real code running in the browser instead of slides.', 27),

  -- Learning Paths (5 new - display_order continues from 0022's 0-4)
  ('learning-path:web-dev-learn', 'learning-path', 'web-dev-learn', 'web.dev Learn', 'Google / web.dev', 'Google''s own structured, modern curriculum on HTML, CSS, JavaScript, performance, accessibility and PWAs.', 'intermediate', 'free', 'https://web.dev/learn/', '🕸️', true, true, '{"Web Dev","Performance","Google"}', 'Written by the Chrome team itself, so the performance and accessibility guidance reflects how the browser actually behaves - not third-party guesswork about best practices.', 5),
  ('learning-path:rust-book', 'learning-path', 'rust-book', 'The Rust Programming Language ("The Book")', 'Rust Foundation', 'The official, canonical guide to Rust - ownership, borrowing, concurrency and the standard library, from the language''s own maintainers.', 'intermediate', 'free', 'https://doc.rust-lang.org/book/', '🦀', false, true, '{"Rust","Systems Programming","Official Docs"}', 'Rarely does a language''s official documentation double as its best teaching material - this is the one language community where reading the manual is genuinely the recommended way to learn.', 6),
  ('learning-path:launch-school', 'learning-path', 'launch-school', 'Launch School', 'Launch School', 'A slow, mastery-based path to becoming a software engineer - depth over speed, with a real emphasis on fundamentals before frameworks.', 'beginner', 'paid', 'https://launchschool.com/', '🚀', false, true, '{"Fundamentals","Mastery-Based","Career Change"}', 'Deliberately the opposite of a 12-week bootcamp promise - the mastery-based pacing means you don''t move on until you''ve actually internalized the fundamentals most programs rush past.', 7),
  ('learning-path:google-cloud-machine-learning-learning-path', 'learning-path', 'google-cloud-machine-learning-learning-path', 'Machine Learning & AI Learning Path', 'Google Cloud', 'Google Cloud''s structured sequence of courses and labs from ML foundations through the Professional ML Engineer certification.', 'intermediate', 'free', 'https://cloud.google.com/learn/training/machinelearning-ai', '🤖', false, true, '{"Machine Learning","Google Cloud","Learning Path"}', 'Structured the way Google actually trains its own ML engineers internally - a real progression toward the Professional ML Engineer cert rather than a loose collection of unrelated videos.', 8),
  ('learning-path:django-girls-tutorial', 'learning-path', 'django-girls-tutorial', 'Django Girls Tutorial', 'Django Girls', 'A warm, beginner-first tutorial that walks you through building and deploying a real Django blog from scratch.', 'beginner', 'free', 'https://tutorial.djangogirls.org/', '🌸', false, true, '{"Python","Django","Beginner Friendly"}', 'Still one of the best-written beginner tutorials in any language, not just Python - it explains what''s actually happening at each step instead of just what to type.', 9),

  -- Developer Tools (10 new - display_order continues from 0022's 0-7)
  ('developer-tool:zed-editor', 'developer-tool', 'zed-editor', 'Zed', 'Zed Industries', 'A blazing-fast, GPU-accelerated code editor built in Rust, with real-time collaboration and native AI features baked in.', null, 'free', 'https://zed.dev/', '⚡', true, true, '{"Editor","Performance","Collaboration"}', 'Built by the team that made Atom and Electron itself, this time optimized to fix the exact performance complaints they heard for a decade - it genuinely feels instant.', 8),
  ('developer-tool:neovim', 'developer-tool', 'neovim', 'Neovim', 'Neovim', 'A hyperextensible, Vim-based text editor rebuilt for modern plugin architecture, async jobs and Lua scripting.', null, 'free', 'https://neovim.io/', '✏️', false, true, '{"Editor","Terminal","Vim"}', 'The fork that finally gave Vim a modern plugin API - if you already live in the terminal, this is the editor that stops fighting you instead of a fully separate IDE.', 9),
  ('developer-tool:tableplus', 'developer-tool', 'tableplus', 'TablePlus', 'TablePlus', 'A clean, native GUI for managing MySQL, PostgreSQL, SQLite, Redis and more from a single fast interface.', null, 'paid', 'https://tableplus.com/', '🧮', false, true, '{"Database","GUI","Productivity"}', 'The database client that doesn''t feel like enterprise Java software from 2009 - native, fast, and the multi-tab query editor alone is worth switching for.', 10),
  ('developer-tool:insomnia', 'developer-tool', 'insomnia', 'Insomnia', 'Kong', 'An open-source API client for designing, debugging and testing REST, GraphQL and gRPC APIs.', null, 'free', 'https://insomnia.rest/', '🌙', false, true, '{"API","Testing","Open Source"}', 'The open-source alternative developers reach for when Postman starts feeling more like an account-management platform than an API tool.', 11),
  ('developer-tool:raycast', 'developer-tool', 'raycast', 'Raycast', 'Raycast', 'A blazing-fast macOS launcher with a real extension ecosystem - clipboard history, snippets, window management and dev-focused commands.', null, 'free', 'https://www.raycast.com/', '🔦', true, true, '{"Productivity","macOS","Launcher"}', 'Spotlight''s replacement that developers actually evangelize unprompted - the extension store turns it into a real command palette for your entire machine, not just app launching.', 12),
  ('developer-tool:httpie', 'developer-tool', 'httpie', 'HTTPie', 'HTTPie', 'A human-friendly command-line and desktop HTTP client, built to make API testing readable instead of a wall of curl flags.', null, 'free', 'https://httpie.io/', '📡', false, true, '{"API","CLI","HTTP"}', 'Reads the way you''d actually describe an HTTP request out loud - the tool people reach for when curl''s flags stop being memorable.', 13),
  ('developer-tool:linear', 'developer-tool', 'linear', 'Linear', 'Linear', 'A fast, opinionated issue tracker and project management tool built specifically for software teams, not generic project work.', null, 'paid', 'https://linear.app/', '📋', true, true, '{"Project Management","Issue Tracking","Team Tool"}', 'Built by engineers who were visibly tired of Jira''s latency and ceremony - keyboard-first, opinionated about workflow, and the tool most engineering teams switch to and never look back.', 14),
  ('developer-tool:bruno', 'developer-tool', 'bruno', 'Bruno', 'usebruno', 'An open-source, offline-first API client that stores collections as plain text files you can commit to git.', null, 'free', 'https://www.usebruno.com/', '🐻', false, true, '{"API","Open Source","Git-Friendly"}', 'Solves the one thing Postman never fixed - collections live as real files in your repo, reviewable in a pull request, instead of locked inside a cloud account.', 15),
  ('developer-tool:ngrok', 'developer-tool', 'ngrok', 'ngrok', 'ngrok', 'Instantly exposes a local server to the internet with a secure tunnel - the standard tool for testing webhooks and sharing local work.', null, 'free', 'https://ngrok.com/', '🌉', false, true, '{"Networking","Webhooks","Dev Tool"}', 'The default answer to how a webhook reaches your laptop during local development - practically every API''s webhook documentation assumes you already have this installed.', 16),
  ('developer-tool:gitkraken', 'developer-tool', 'gitkraken', 'GitKraken', 'Axosoft', 'A visual Git client that makes branching, merging and resolving conflicts genuinely easier to reason about than the command line.', null, 'paid', 'https://www.gitkraken.com/', '🐙', false, true, '{"Git","GUI","Version Control"}', 'The commit graph visualization is the actual selling point - untangling a messy merge conflict is a different experience when you can see the branch history instead of parsing it from git log --graph.', 17),

  -- Cheat Sheets (8 new - display_order continues from 0022's 0-6)
  ('cheat-sheet:javascript-cheat-sheet', 'cheat-sheet', 'javascript-cheat-sheet', 'JavaScript (ES2015+)', 'devhints.io', 'A dense quick reference for modern JavaScript syntax - destructuring, modules, async/await, classes and array methods.', null, null, 'https://devhints.io/es6', '📜', false, false, '{"JavaScript","Syntax","Quick Reference"}', 'Covers exactly the syntax that trips up developers coming from older JS or another language - genuinely faster to scan than searching MDN mid-task.', 7),
  ('cheat-sheet:react-cheat-sheet', 'cheat-sheet', 'react-cheat-sheet', 'React', 'devhints.io', 'A compact reference for React syntax - hooks, JSX patterns, lifecycle equivalents and common idioms.', null, null, 'https://devhints.io/react', '⚛️', false, false, '{"React","Hooks","Quick Reference"}', 'The one-page version of the React docs you actually pull up mid-task when you''ve blanked on useEffect''s dependency array behavior for the hundredth time.', 8),
  ('cheat-sheet:typescript-cheat-sheet', 'cheat-sheet', 'typescript-cheat-sheet', 'TypeScript', 'devhints.io', 'A quick reference for TypeScript''s type system - generics, utility types, interfaces and common patterns.', null, null, 'https://devhints.io/typescript', '🔷', false, false, '{"TypeScript","Types","Quick Reference"}', 'Utility types (Partial, Pick, Omit and friends) are the thing everyone forgets the exact syntax for - this is the fastest place to double-check it.', 9),
  ('cheat-sheet:sql-cheat-sheet', 'cheat-sheet', 'sql-cheat-sheet', 'SQL', 'SQLTutorial.org', 'A practical reference for core SQL syntax - joins, aggregates, subqueries, window functions and common query patterns.', null, null, 'https://www.sqltutorial.org/sql-cheat-sheet/', '🗃️', false, false, '{"SQL","Database","Quick Reference"}', 'Complements the existing PostgreSQL sheet with standard, engine-agnostic SQL syntax - useful the moment you''re working against MySQL, SQLite or anything that isn''t Postgres.', 10),
  ('cheat-sheet:vim-cheat-sheet', 'cheat-sheet', 'vim-cheat-sheet', 'Vim', 'devhints.io', 'A concise reference for Vim''s modal editing commands - motions, registers, macros and common workflows.', null, null, 'https://devhints.io/vim', '📗', false, false, '{"Vim","Terminal","Quick Reference"}', 'The single most bookmarked page for anyone learning modal editing - motions and text objects finally start to click once you see them laid out together like this.', 11),
  ('cheat-sheet:markdown-cheat-sheet', 'cheat-sheet', 'markdown-cheat-sheet', 'Markdown', 'devhints.io', 'A quick reference for Markdown syntax - headers, tables, links, code blocks and GitHub-flavored extensions.', null, null, 'https://devhints.io/markdown', '📝', false, false, '{"Markdown","Writing","Quick Reference"}', 'Table syntax and footnotes are the two things everyone re-Googles every single time - this sheet ends that cycle.', 12),
  ('cheat-sheet:tmux-cheat-sheet', 'cheat-sheet', 'tmux-cheat-sheet', 'tmux', 'devhints.io', 'A quick reference for tmux - sessions, windows, panes, key bindings and common terminal multiplexing workflows.', null, null, 'https://devhints.io/tmux', '🖥️', false, false, '{"tmux","Terminal","Quick Reference"}', 'Once you SSH into a remote box for real work, tmux stops being optional - this is the sheet that gets you past the first confusing five minutes of prefix-key combos.', 13),
  ('cheat-sheet:terraform-cheat-sheet', 'cheat-sheet', 'terraform-cheat-sheet', 'Terraform CLI Commands', 'Spacelift', 'A comprehensive quick reference for Terraform CLI commands - plan, apply, state management, workspaces and common flags.', null, null, 'https://spacelift.io/blog/terraform-commands-cheat-sheet', '🧱', false, false, '{"Terraform","IaC","Quick Reference"}', 'Pairs naturally with the Terraform Associate certification already in the catalog - state and workspace commands are exactly the flags people blank on mid-incident.', 14)
on conflict (id) do nothing;

-- file_type for the cheat sheets seeded above (same pattern as 0022 - kept
-- as a separate UPDATE rather than a column in the shared insert above).
update public.catalog_items set file_type = 'Web' where id in ('cheat-sheet:javascript-cheat-sheet', 'cheat-sheet:react-cheat-sheet', 'cheat-sheet:typescript-cheat-sheet', 'cheat-sheet:vim-cheat-sheet', 'cheat-sheet:markdown-cheat-sheet', 'cheat-sheet:tmux-cheat-sheet', 'cheat-sheet:terraform-cheat-sheet');
update public.catalog_items set file_type = 'PDF' where id in ('cheat-sheet:sql-cheat-sheet');

-- ============================================================================
-- Part 2b: Roadmaps (9 new, all roadmap.sh) - separate insert shape, same
-- as 0022 (estimated_time + steps instead of price/official).
-- ============================================================================

insert into public.catalog_items (id, resource_type, slug, title, provider, description, difficulty, url, emoji, featured, estimated_time, steps, tags, editor_notes, display_order)
values
  ('roadmap:roadmap-full-stack', 'roadmap', 'roadmap-full-stack', 'Full Stack Developer', 'roadmap.sh', 'A step-by-step guide combining the frontend and backend roadmaps into one path toward full-stack proficiency.', 'intermediate', 'https://roadmap.sh/full-stack', '🧭', false, '6-10 months', array['Frontend', 'Backend', 'Databases', 'APIs', 'Deployment'], '{"Full Stack","Roadmap","Career Path"}', 'For the developer who''s outgrown thinking in just-frontend or just-backend terms - a genuinely honest sequencing of what to learn next rather than everything at once.', 6),
  ('roadmap:roadmap-data-structures-algorithms', 'roadmap', 'roadmap-data-structures-algorithms', 'Data Structures & Algorithms', 'roadmap.sh', 'A structured path through core CS fundamentals - arrays, trees, graphs, sorting and complexity analysis - for interviews and real engineering judgment.', 'intermediate', 'https://roadmap.sh/datastructures-and-algorithms', '🧮', false, '3-6 months', array['Complexity', 'Arrays & Strings', 'Trees & Graphs', 'Sorting', 'Dynamic Programming'], '{"DSA","Interview Prep","Fundamentals"}', 'Useful well beyond interview prep - the roadmap doubles as a checklist for the CS fundamentals bootcamps and self-taught paths often skip entirely.', 7),
  ('roadmap:roadmap-system-design', 'roadmap', 'roadmap-system-design', 'System Design', 'roadmap.sh', 'A guide to designing large-scale distributed systems - load balancing, caching, sharding, consistency and real architectural trade-offs.', 'advanced', 'https://roadmap.sh/system-design', '🏗️', true, '4-8 months', array['Networking Basics', 'Caching', 'Databases at Scale', 'Load Balancing', 'Trade-offs'], '{"System Design","Architecture","Scalability"}', 'The topic senior engineering interviews actually hinge on - this roadmap is a solid map of the trade-off vocabulary you need before your first whiteboard session.', 8),
  ('roadmap:roadmap-software-architect', 'roadmap', 'roadmap-software-architect', 'Software Architect', 'roadmap.sh', 'A path from senior engineer toward software architecture - system design, architectural styles, communication and technical leadership.', 'advanced', 'https://roadmap.sh/software-architect', '🏛️', false, '8-12 months', array['Architectural Styles', 'Design Patterns', 'System Design', 'Documentation', 'Leadership'], '{"Architecture","Leadership","Career Path"}', 'Covers the part of the architect transition most engineers underestimate - the roadmap spends as much time on communication and documentation as it does on technical patterns.', 9),
  ('roadmap:roadmap-qa-engineer', 'roadmap', 'roadmap-qa-engineer', 'QA Engineer', 'roadmap.sh', 'A modern QA path covering manual testing fundamentals, test automation, CI integration and performance/security testing.', 'beginner', 'https://roadmap.sh/qa', '🧪', false, '3-6 months', array['Testing Fundamentals', 'Automation', 'CI Integration', 'API Testing', 'Performance'], '{"QA","Testing","Automation"}', 'Treats QA as real engineering rather than an afterthought - the automation and CI sections are what separate a modern QA path from clicking through manual test cases.', 10),
  ('roadmap:roadmap-python', 'roadmap', 'roadmap-python', 'Python Developer', 'roadmap.sh', 'A structured path through Python fundamentals, web frameworks, testing and deployment for building real applications.', 'beginner', 'https://roadmap.sh/python', '🐍', false, '3-6 months', array['Syntax & Basics', 'OOP', 'Web Frameworks', 'Testing', 'Deployment'], '{"Python","Roadmap","Backend"}', 'Skips the long stretch of Hello World repetition most tutorials get stuck in and gets to frameworks and real deployment fairly quickly.', 11),
  ('roadmap:roadmap-react', 'roadmap', 'roadmap-react', 'React Developer', 'roadmap.sh', 'A step-by-step guide to React - hooks, state management, routing, testing and the surrounding ecosystem, kept current.', 'intermediate', 'https://roadmap.sh/react', '⚛️', false, '3-5 months', array['JSX & Components', 'Hooks', 'State Management', 'Routing', 'Testing'], '{"React","Frontend","Roadmap"}', 'Actually maintained as the ecosystem shifts - genuinely useful for cutting through the constant churn of is-Redux-still-the-answer debates with a clear, current sequence.', 12),
  ('roadmap:roadmap-data-engineer', 'roadmap', 'roadmap-data-engineer', 'Data Engineer', 'roadmap.sh', 'A path through data pipelines, warehousing, orchestration and the modern data stack, from fundamentals to production systems.', 'intermediate', 'https://roadmap.sh/data-engineer', '🛢️', false, '6-10 months', array['SQL & Databases', 'ETL/ELT', 'Orchestration', 'Data Warehousing', 'Streaming'], '{"Data Engineering","Pipelines","SQL"}', 'One of the least-served roles by generic learning content - this roadmap is a rare structured answer to what you actually need beyond SQL for the job.', 13),
  ('roadmap:roadmap-kubernetes', 'roadmap', 'roadmap-kubernetes', 'Kubernetes', 'roadmap.sh', 'A dedicated, deep path through Kubernetes - pods, deployments, networking, storage and operating real clusters in production.', 'advanced', 'https://roadmap.sh/kubernetes', '☸️', false, '4-8 months', array['Core Concepts', 'Networking', 'Storage', 'Workloads', 'Operations'], '{"Kubernetes","DevOps","Containers"}', 'Goes deeper than the general DevOps roadmap''s Kubernetes section - the right next step once kubectl-apply-and-hope stops being an acceptable operating strategy.', 14)
on conflict (id) do nothing;
